# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX = ENV.fetch('BOX', 'fedora/37-cloud-base')
DRIVER = ENV.fetch('DRIVER', 'qemu')

Vagrant.configure("2") do |config|
  # TODO:
  #, type: "nfs"
  #, type: "sshfs"
  config.vm.synced_folder ".", "/lizmap"

  config.vm.box = BOX

  config.vm.provider :libvirt do |lv|
    lv.driver = DRIVER
  end
end
