BOX = ENV.fetch('BOX', 'fedora/37-cloud-base')
DRIVER = ENV.fetch('DRIVER', 'qemu')

Vagrant.configure("2") do |config|
  config.vm.box = BOX

  config.vm.provider :libvirt do |lv|
    lv.driver = DRIVER
    lv.storage :file, :size => '5G'
  end
end
