# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/37-cloud-base"

  config.vm.provider :libvirt do |lv|
   lv.management_network_name = 'vagrant-libvirt-new'
   lv.management_network_address = '192.168.124.0/24'
  end
end
