# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/37-cloud-base"

  config.vm.provider :libvirt do |lv|
    lv.driver = "qemu"
    lv.qemu_use_session = false
  end
end
