# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX = ENV.fetch('BOX', 'fedora/37-cloud-base')
DRIVER = ENV.fetch('DRIVER', 'qemu')

Vagrant.configure("2") do |config|
  config.vm.hostname = "this.is.my.vagrant.box"

  config.vm.box = BOX

  config.vm.provider :libvirt do |lv|
    lv.driver = DRIVER
  end
end
